# Generated by Django 5.1 on 2024-08-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0003_customuser_is_superuser_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
